/**
 * The canonical build: `pnpm run build`, run from the repository root.
 *
 * Two passes, because the repository has two kinds of module:
 *
 *   1. `src/*.ts` — TypeScript sources, emitted to `lib/` as JavaScript
 *      plus their declarations (`tsconfig.build.json`).
 *   2. `lib/*.js` — the hand-written, JSDoc-typed modules, which get
 *      declarations only (`tsconfig.dts.json`, `emitDeclarationOnly`).
 *
 * Pass 2 must run against a CLEAN tree. A `.d.ts` left over from a previous
 * build sits exactly where TypeScript resolves `./x.js` and is picked up as an
 * input, and re-emitting through it silently DEGRADES the result — a place
 * that resolved to a precise type collapses to `any`. So every declaration
 * pass 1 does not own is deleted first and regenerated by pass 2; the deleted
 * files are build products by definition. A failed pass therefore leaves the
 * affected declarations missing rather than stale, which `lint:build` reports
 * loudly on the next run.
 *
 * The declarations stay beside their JavaScript (same directory, same export
 * paths), and the artifacts stay committed — see CONTRIBUTING, "The build".
 */
import { execFileSync } from "node:child_process";
import { readdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const TSC = join(ROOT, "node_modules", "typescript", "bin", "tsc");

/**
 * Run one build config, inheriting stdio so compiler errors are visible.
 * @param {string} config - the build config to run.
 */
function build(config) {
  execFileSync(process.execPath, [TSC, "-p", join(ROOT, config)], { cwd: ROOT, stdio: "inherit" });
}

/**
 * The declaration basenames pass 1 owns: one per `src/*.ts`, beside the
 * JavaScript it emits.
 * @returns {Set<string>} basenames under `lib/`.
 */
function firstPassDeclarations() {
  return new Set(
    readdirSync(join(ROOT, "src"))
      .filter((name) => name.endsWith(".ts"))
      .map((name) => `${name.slice(0, -3)}.d.ts`),
  );
}

build("tsconfig.build.json");

const owned = firstPassDeclarations();
for (const name of readdirSync(join(ROOT, "lib"))) {
  if (name.endsWith(".d.ts") && !owned.has(name)) rmSync(join(ROOT, "lib", name));
}

build("tsconfig.dts.json");
